[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "qiskit_resource_estimation"
version = "0.1.0"
description = "Estimate FTQC algorithm resources"
dependencies = ["qiskit>=2.4", "mpmath"]

[tool.setuptools]
packages = ["qiskit_resource_estimation"]

# development dependencies only (not included in built distribution)
[dependency-groups]
examples = [ # dependency group for running the examples
  "matplotlib",
]
dev = ["black", "ruff", "pyrefly", "ddt"]

[tool.black]
line-length = 100

[tool.ruff]
line-length = 105

[tool.ruff.lint]
# Add the `line-too-long` rule to the enforced rule set. By default, Ruff omits rules that
# overlap with the use of a formatter, like Black, but we can override this behavior by
# explicitly adding the rule.
extend-select = ["E501"]

[tool.pyrefly]
project-includes = ["**/*.py"]
project-excludes = ["examples/**"]
