# Copyright IBM 2026

"""Tests for BicycleErrorModel / GrossErrorModel behaviour."""

import unittest
import numpy as np
from qiskit.circuit import QuantumCircuit

from qiskit_resource_estimation.graphs.callgraph import CallGraph
from qiskit_resource_estimation.graphs.nodes import InstructionNode
from qiskit_resource_estimation.graphs.metrics import Fidelity
from qiskit_resource_estimation.error_models import GrossErrorModel
from qiskit_resource_estimation.topologies import Linear


class TestGrossErrorModel(unittest.TestCase):
    def setUp(self):
        self.topo = Linear(num_modules=1)
        self.model = GrossErrorModel(topology=self.topo, p=3)

    def fidelity(self, circuit: QuantumCircuit, basis: list[str] | None = None) -> float:
        graph = CallGraph.from_circuit(circuit)
        result = graph.estimate(error_models={InstructionNode: self.model}, basis=basis)
        return float(result[Fidelity()])

    def test_pauli_and_reset_circuit_has_fidelity_one(self):
        """Circuits containing only Pauli gates and resets carry no error."""
        qc = QuantumCircuit(2)
        qc.reset(0)
        qc.x(0)
        qc.y(1)
        qc.z(0)
        qc.reset(1)
        qc.x(1)

        self.assertAlmostEqual(self.fidelity(qc), 1.0)

    def test_same_shape_different_angle_class_evaluated_independently(self):
        """Regression test: estimate() must not conflate rz gates of different angle class.

        This test was generated by Claude Sonnet 5 (and then modified).
        """
        qc_clifford = QuantumCircuit(1)
        qc_clifford.rz(np.pi / 2, 0)  # Clifford-like angle

        qc_rotation = QuantumCircuit(1)
        angle = 0.817263
        qc_rotation.rz(angle, 0)  # arbitrary angle

        qc_both = QuantumCircuit(1)
        qc_both.rz(np.pi / 2, 0)
        qc_both.rz(angle, 0)

        expected = self.fidelity(qc_clifford, basis=["rz"]) * self.fidelity(
            qc_rotation, basis=["rz"]
        )
        self.assertAlmostEqual(self.fidelity(qc_both, basis=["rz"]), expected)


if __name__ == "__main__":
    unittest.main()
