# Copyright IBM 2026

"""Exact operator-norm scaling of the 1st order Trotter error for the linear TFIM.

Builds the linear transverse-field Ising Hamiltonian H = J * sum ZZ + h * sum X,
computes the exact time evolution exp(-i H t) and the 1st order (Lie-Trotter)
approximation of it, and compares them in operator norm as a function of the
number of qubits n, for a fixed small time t. This is contrasted against the
loose analytic upper bound t^2 * 2 * J * h * (n - 1) used elsewhere in this repo
(see examples/qpe_scaling and examples/hyperparameter_optimization/optimization.py).

The Hamiltonian and the Trotter step are built and multiplied out as sparse
matrices (each Trotter factor is a 1- or 2-qubit gate embedded into the full
space, so the running product stays genuinely sparse). The exact evolution
exp(-i H t), however, is fundamentally dense for a generic interacting
Hamiltonian: `scipy.sparse.linalg.expm` still fills in completely during its
Pade/scaling-and-squaring steps, just slower than a dense LAPACK `expm` since
it does the same fill-in work through sparse-format arithmetic. So the exact
evolution is computed densely (this is the actual bottleneck and caps the
feasible range at n ~ 12-13, sparse or not), while the Trotter side is kept
sparse throughout and only densified at the final difference/norm step.

--

This file has been generated by Claude Sonnet 5
"""

import numpy as np
import matplotlib.pyplot as plt
import scipy.sparse as sp
from scipy.linalg import expm

from qiskit.circuit.library import PauliEvolutionGate
from qiskit.circuit import QuantumCircuit
from qiskit.quantum_info import SparsePauliOp

COUPLING_CONST = 0.5
FIELD_CONST = 1.0


def build_ising_hamiltonian(num_qubits: int) -> SparsePauliOp:
    return SparsePauliOp.from_sparse_list(
        [("ZZ", [i, i + 1], COUPLING_CONST) for i in range(num_qubits - 1)]
        + [("X", [i], FIELD_CONST) for i in range(num_qubits)],
        num_qubits=num_qubits,
    )


def exact_evolution_dense(hamiltonian: SparsePauliOp, time: float) -> np.ndarray:
    # exp(-i H t) is dense for a generic interacting H, so sparse expm buys nothing
    # here (it does the same fill-in work, just slower); build H sparsely and only
    # densify right before the matrix exponential.
    h_dense = hamiltonian.to_matrix(sparse=True).toarray()
    return expm(-1j * time * h_dense)


def trotter_evolution_sparse(hamiltonian: SparsePauliOp, time: float) -> sp.csr_matrix:
    num_qubits = hamiltonian.num_qubits
    gate = PauliEvolutionGate(hamiltonian, time=time)
    circuit = QuantumCircuit(num_qubits)
    circuit.append(gate, circuit.qubits)
    definition = circuit.decompose()

    unitary = sp.identity(2**num_qubits, format="csr", dtype=complex)
    for instruction in definition.data:
        qubits = [definition.find_bit(q).index for q in instruction.qubits]
        gate_matrix = sp.csr_matrix(instruction.operation.to_matrix(), dtype=complex)
        unitary = _embed_gate(gate_matrix, qubits, num_qubits) @ unitary
    return unitary


def _embed_gate(gate_matrix: sp.spmatrix, qubits: list[int], num_qubits: int) -> sp.csr_matrix:
    """Embed a 1- or 2-qubit gate (acting on adjacent qubits) into the full n-qubit space."""
    low = min(qubits)
    high = max(qubits)
    if high - low + 1 != len(qubits):
        raise ValueError("only gates acting on contiguous qubits are supported")

    result = gate_matrix
    if low > 0:
        result = sp.kron(result, sp.identity(2**low, format="csr", dtype=complex), format="csr")
    if high < num_qubits - 1:
        tail = sp.identity(2 ** (num_qubits - high - 1), format="csr", dtype=complex)
        result = sp.kron(tail, result, format="csr")
    return result


def operator_norm_error(exact: np.ndarray, approx: sp.spmatrix) -> float:
    diff = exact - approx.toarray()
    return float(np.linalg.norm(diff, ord=2))


def loose_upper_bound(num_qubits: int, time: float) -> float:
    return time**2 * 2 * COUPLING_CONST * FIELD_CONST * (num_qubits - 1)


def scan_num_qubits(qubit_range: range, time: float) -> np.ndarray:
    errors = np.empty(len(qubit_range))
    for idx, num_qubits in enumerate(qubit_range):
        hamiltonian = build_ising_hamiltonian(num_qubits)
        exact = exact_evolution_dense(hamiltonian, time)
        approx = trotter_evolution_sparse(hamiltonian, time)
        errors[idx] = operator_norm_error(exact, approx)
    return errors


def plot(time: float = 0.01, max_qubits: int = 12, min_qubits: int = 2, extrapolate_to: int = 500):
    qubit_range = range(min_qubits, max_qubits + 1)
    errors = scan_num_qubits(qubit_range, time)
    bounds = np.array([loose_upper_bound(n, time) for n in qubit_range])

    # fit error ~ c * n^alpha on the actual (non-bound) data
    log_n = np.log(np.array(list(qubit_range)))
    alpha, log_c = np.polyfit(log_n, np.log(errors), 1)

    extrap_range = np.arange(max_qubits, extrapolate_to + 1)
    extrap_fit = np.exp(log_c) * extrap_range**alpha
    extrap_bound = np.array([loose_upper_bound(n, time) for n in extrap_range])

    _, ax = plt.subplots(figsize=(6, 4.5))
    ax.loglog(qubit_range, errors, "o-", c="royalblue", label="exact operator-norm error")
    ax.loglog(qubit_range, bounds, "--", c="firebrick", label=r"loose bound $t^2 \cdot 2Jh(n-1)$")
    ax.loglog(
        qubit_range,
        np.exp(log_c) * np.array(list(qubit_range)) ** alpha,
        ":",
        c="seagreen",
        label=rf"fit $\propto n^{{{alpha:.2f}}}$",
    )
    ax.loglog(extrap_range, extrap_fit, ":", c="seagreen", alpha=0.5)
    ax.loglog(
        extrap_range,
        extrap_bound,
        "--",
        c="firebrick",
        alpha=0.5,
        label=f"extrapolated (n>{max_qubits}, not simulated)",
    )
    ax.axvline(max_qubits, c="gray", lw=0.8, ls=":")
    ax.set_xlabel("number of qubits $n$")
    ax.set_ylabel(r"$\|\|U_{\mathrm{exact}} - U_{\mathrm{Trotter}}\|\|_2$")
    ax.set_title(f"1st order Trotter error scaling (t={time})")
    ax.legend(fontsize=8)
    plt.tight_layout()
    plt.show()

    print(f"fitted scaling exponent: alpha = {alpha:.3f}")
    print(
        f"extrapolated error at n={extrapolate_to}: fit={extrap_fit[-1]:.3e}, bound={extrap_bound[-1]:.3e}"
    )


if __name__ == "__main__":
    plot()
